function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Derives 1/N-octave and octave band spectra using FFT bin data. ', ...
    ' IEC (ANSI) frequency bands are used', ...
    ' FFT bins are mapped to 1/N-octave bands', ...
    ' ', ...
    'Input Parameters are:' ...
    '* NOct - integer "N" from 1/N-octave' ...
    '* NOctStartHz - centre frequency of first 1/N-octave band' ...
    '* NOctType - 1-> ansi; 2-> music' ...
    '* NOct_WindowLength - FFT window size' ...
    '* NOct_WindowType - FFt window type' ...
    '* NOct_OverlapSize - FFT overlap' ...
    '* NOct_OverlapType - FFT overlap type' ...
    '* NOct_LevelOffset - FFT level offset' ...
    ' ', ...
    'Calculated Parameters are:' ...
    '* NOctG - calculated from NOctType' ...
    '* NOctNumBands - number of 1/N-octave bands' ...
    '* NOctCentreFreq - vector of 1/N-octave band centre frequencies' ...
    '* NOct_FFT_2_NOctFreq - vector mapping FFT bins to 1/N-octave bands' ...
    ' ', ...
    'Outputs are:', ...
    '* 1/N-Octave band spectrogram', ...
    '* 1/N-Octave band spectrum,', ...
    'Standardized and non-standardized power spectral moments, such as', ...
    '* Centroid', ...
    '* Standard deviation', ...
    '* Skewness', ...
    '* Kurtosis'};
