function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Performs auto-correlation and interaural cross-correlation', ...
        'analysis to obtain parameters described by Yoichi Ando.', ...
        ' ', ...
        'Input must be a 2-channel sound file,', ...
        'and should be binaural.', ...
        ' ', ...
        'A-weighting is applied to the analysis data.', ...
        ' ', ...
        'Outputs are:', ...
        '* Auto-correlation parameters (tau1, phi1 and taue)',...
        '  for left and right channels', ...
        '* Cross-correlation parameters', ... 
        '  (phi0, iacc, tauiacc and Wiacc)', ...
        '* Left and right auto-correlograms, and', ...
        '* Cross-correlogram.', ...
        ' ', ...
        'Key Reference: Y. Ando, ''Architectural Acoustics''', ...
        'Springer-Verlag, 1998.', ...
        ' ', ...
        'Adapted from code provided by Shin-ichi Sato.'};

