function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Calculates loudness, loudness fluctuation', ... 
    'and related parameters ', ...
    'using the loudness model of Chalupper and Fastl: ', ...
    ' ', ...
    'J. Chalupper & H. Fastl (2002) "Dynamic Loudness Model', ... 
    '(DLM) for Normal and Hearing-Impaired Listeners,"', ...
    'Acta Acustica United with Acustica, 88:378-386, 2002. ', ...
       'J. Chalupper (2000) "Modellierung der', ...
       'Lautstärkeschwankung für Normal- ', ...
       'und Schwerhörige," in DAGA 2000, 254-255. ', ...
       ' ', ...
       'Outputs include: ', ...
       '* Specific loudness spectrogram ', ...
       '* Time averaged pecific loudness pattern ', ...
       '* Loudness ', ...
       '* Sharpness (Zwicker & Fastl)', ...
       '* Loudness fluctuation ', ...
       ' ', ...
       'Source code was provided by Josef Chalupper', ...
       'and adapted by the PsySound team.'};   

