function analysers = getDataAnalysers()
% GETDATAANALYSERS Return the Analysers in this directory

path = fileparts(mfilename('fullpath'));   % find this directory
analysers = what(path);                    % What's in this directory
analysers = analysers.classes;             % Specifically, which classes are in this directory

analyserOrder = {'BasicPlot', ...
             'SummaryBasic', ...
             'ComparisonPlot', ...
             'DataExportBasic', ...
             'DataExportGroup', ...
             'AnimationPlot', ...
             'ExploratorySoundAnalysis', ...
             'AllAvgSpec', ...
             'FastFourierTransform', ...
             'DownSampling',...
             'CrossCorr',...
             'AutoCorr'};

% compare to list of analysers to find new ones
newAnalysers = [];
for i = 1: length(analysers)
  if ~sum(strcmp(analysers{i},analyserOrder))
    newAnalysers = [newAnalysers i];
  end
end
analyserOrder(end+1:end+length(newAnalysers)) =  analysers(newAnalysers);
analysers = analyserOrder'; 



% there are some analysers we never want to return - list them here
analysersToHide = {'DataAnalyser','AuditoryGraphing'};
an =[];
for i = 1:length(analysers)
	for j = 1: length(analysersToHide)
		if  strcmp(analysers{i},analysersToHide{j})
		  an = [an i];% remember indexes to kill off later
		end
	end
end
% hide these inappropriate analysers by taking them from the list
analysers(an) = [];


if length(analysers) > 2
	return
end
% If something's gone wrong default to list below       

analysers = {'BasicPlot', ...
             'SummaryBasic', ...
             'StatisticsBasic', ...
             'ComparisonPlot', ...
             'DataExportBasic', ...
             'DataExportGroup', ...
             'AnimationPlot', ...
             'ExploratorySoundAnalysis', ...
             'AllAvgSpec', ...
             'FastFourierTransform', ...
             'DownSampling',...
             'CrossCorr',...
             'AutoCorr'};

% EOF
