function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Derives 1/12-octave and octave band spectra using FFT. ', ...
    ' IEC frequency bands are used (not musical frequencies)', ...
    ' 1 and 2 channel file analysis', ...
    ' ', ...
    'Outputs are:', ...
    '* 1/12-Octave band spectrogram', ...
    '* 1/12-Octave band spectrum,', ...
    '* Inter-channel difference spectrogram & spectrum'};
