function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'MIRPITCH algorithm from MIRTOOLBOX 1.3.4',...
    '',...
    ' Olivier Lartillot, Petri Toiviainen, "A Matlab Toolbox for',...
    'Musical Feature Extraction From Audio"',...
    'International Conference on Digital Audio Effects, Bordeaux, 2007.',...
    '',...
   ' Olivier Lartillot, Petri Toiviainen, Tuomas Eerola,'...
   '"A Matlab Toolbox for Music Information Retrieval"',...
   'in C. Preisach, H. Burkhardt, L. Schmidt- Thieme, R. Decker (Eds.),',...
   'Data Analysis, Machine Learning and Applications,',...
   'Studies in Classification, Data Analysis,',...
   'and Knowledge Organization, Springer-Verlag, 2008.',...
   '',...
   ' Please check the "MirToolbox-UserManual.pdf" in the'...
   '"Documentation" folder}'};