function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Performs a Hilbert transform of the input wave. ', ...
    ' ', ...
      'Outputs are: ', ...
  '* instantaneous level (or Hilbert envelope function); ', ...
  '* instantaneous frequency; ', ...
  '* instantaneous phase.'};