function ui(obj, parent)
% Sets up the ui for the LoudnessMGB Analyser. 
% usage: ui(FFT, parent)
% 
% We rely on picking up the Tag of the uicontrol objects later, so we only
% set them up, we don't return handles to each of them. We can get the handles 
% again in the settings method with handle = findobj('Tag','YourTagHere');
% 
% Make sure the tags you use are unique. The easiest way to do this is to
% use the name of the analyser in the tag at the start, as is done below. 

objName = get(obj, 'Name');

% A popup menu, with some text above it.       
textString = textwrap({'Choose Filter Method:'}, 40);
uicontrol('Style', 'text', ...
          'FontSize', 9, ...
          'String', textString,...
          'Parent', parent, ...
          'Units', 'Characters', ...
          'Position', [1 18 46 1],...
          'HorizontalAlignment', 'left', ...
          'BackgroundColor', [0.9 0.9 0.9]);
        
 uicontrol('Style', 'popup', ...
          'String', 'Free field 1|Free field 2|Middle ear 1|Middle ear 2',...
          'Parent', parent, ...
          'Tag', [class(obj), 'FilterType'], ...
          'Units', 'Characters',...
          'Position', [1 15 20 2], ...
          'BackgroundColor',[0.9 0.9 0.9]);