function obj = ui(obj, panel)
% UI method for Data Analyser.  This is a default method that
%    provides a single pushbutton for convenience.
%
% Inputs:
%  panel : is the handle to the left panel of the data analyser

bgColor = [0.9 0.9 0.9];

% Add Execute push-button
uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.7 0.1 0.15 0.07], ...
          'String',  'Process', ...
          'Callback', @(src, ev)process(obj, src), ...          
          'Style',   'Pushbutton');

% Add checkboxes
uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.7 0.2 0.3 0.05], ...
          'BackGroundColor', bgColor, ...              
          'String',  'Graph Smoothness Spectrum', ...
          'HorizontalAlignment', 'right', ...
          'Style',   'Checkbox', ...
					'Tag', 'PeriodicityGraphSmoothness');

uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.7 0.3 0.3 0.05], ...
          'BackGroundColor', bgColor, ...              
          'String',  'Graph Rate and Extent', ...
          'HorizontalAlignment', 'right', ...
          'Style',   'Checkbox', ...
					'Tag', 'PeriodicityGraphRateExt');


% EOF
