function x = mirframenow(x,option)

if isfield(option,'frame') && ...
        isstruct(option.frame) && option.frame.length.val
    x = mirframe(x,...
        option.frame.length.val,option.frame.length.unit,...
        option.frame.hop.val,option.frame.hop.unit);
end