function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Derives 1/12-octave spectrum using Brown & Puckette''s', ...
    ' Fast constant-Q transform.', ...
    ' Music frequencies (12TET, A440) are used.', ...
    ' 1 and 2 channel file analysis', ...
    ' ', ...
    'Outputs are:', ...
    '* 1/12-Octave band spectrogram', ...
    '* 1/12-Octave band spectrum,', ...
    '* Inter-channel difference spectrogram & spectrum'...
    ' ', ...
    'Sources:',...
    'JC Brown & MS Puckette, 1992, An efficient algorithm for',...
    'the calculation of a constant Q transform, JASA 92(5)',...
    ' '...
    'Core analysis code by Benjamin Blankertz',...
    'http://wwwmath.uni-muenster.de/logik/Personen/',...
    'blankertz/constQ/constQ.html'};
