
function cells = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

cells = {'Performs successive auto-correlations ',  ...
    'of the input wave.',  ...
    'Auto-correlations are linear (not circular). ', ...
       'Each auto-correlation function is normalised, ', ...
       'so results are unaffected by calibration. ',  ...
       ' ', ...
       'Outputs are:',          ...
       '* autocorrelogram',   ...
       '* mean auto-correlation function', ...
       '* peak frequency of each auto-correlation function', ...
       '* peak height of each auto-correlation funciton.'};