function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Emulates a sound level meter with ', ...
       'user-selectable weighting filters (A, B, C, Z)', ...
       'and integration times (fast and slow). ' ,...
       'Outputs are time series corresponding', ...
       'to the selected analysis settings.'};