function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Calculates sound pressure level using the Revised ',...
       'Low-frequency B-curve (RLB) weightings ',      ...
       'followed by RMS (rectangular) integration.', ...
       ' ', ....
       'Key references:', ....
       'G. A. Soulodre (2004) “Evaluation of', ...
       'objective loudness meters,” 116th Audio', ... 
       'Engineering Society Convention, Berlin.', ...
       ' ', ....
       'G. A. Soulodre and M. C. Lavoie (2006)', ...
       '“Development and evaluation of short-term', ...
       'loudness meters,” 121st Audio Engineering', ...
       'Society Convention, San Francisco.'};
