function ui(obj, panel)
% UI method 
% Inputs:
%  panel : is the handle to the left panel of the data analyser

% Make textboxes to be filled by the selected timeseries objects.
%
% Make autofilled max,min boxes 
% 
% Make button for sonify.
%
% Make button for export wavfile

%%%%%% Sonification panel

h = uicontrol('Parent',  panel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Normalized',...
              'Position', [0.1 0.2 0.1 0.1], ...
              'String', 'Min.', ...
              'BackgroundColor', bgColor);

h = uicontrol('Parent',  panel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Normalized',...
              'Position', [0.2 0.2 0.1 0.1], ...
              'String', 'Max.', ...
              'BackgroundColor', bgColor);



sonicCellStrs = {'Frequency (Hz)', 'Level (dB)', 'Pan 0:L, 1:R'};
sonicCellTags = {'freq', 'level', 'pan'};
  pos{1} =  [0.5 0.5 0.05 0.05; 
		  0.5 0.5 0.05 0.05;
		  0.5 0.5 0.05 0.05];
pos{2} =  [0.5 0.5 0.05 0.05; 
		  0.5 0.5 0.05 0.05;
		  0.5 0.5 0.05 0.05];
pos{3} =  [0.5 0.5 0.05 0.05; 
		  0.5 0.5 0.05 0.05;
		  0.5 0.5 0.05 0.05];
		
  str = sonicCellStrs{1};
  tag = sonicCellTags{1};

  % TSObj
  h = uicontrol('Parent',  panel, ...
                'Style', 'edit', ...
                'Units', 'Normalized',...
                'Fontsize', 9, ...
                'Position', rowPos, ...
                'String', '', ...
                'Tag', [tag, 'TsObj']);

  h = uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'FontSize', 9, ...
                'Units', 'Normalized', ...
                'Position', pos{1}(1,:), ...
                'HorizontalAlignment', 'right',...
                'String', str, ...
                'BackgroundColor', bgColor);

  h = uicontrol('Parent',  panel, ...
                'Style', 'edit', ...
                'Units', 'Normalized',...
                'Fontsize', 9, ...
                'Position', pos{1}(2,:), ...
                'String', '0', ...
                'Enable', 'off', ...
                'Tag', [tag, 'Min']);

  h = uicontrol('Parent',  panel, ...
                'Style', 'edit', ...
                'Units', 'Normalized',...
                'Fontsize', 9, ...
                'Position', pos{1}(3,:), ...
                'String', '0', ...
                'Enable', 'off', ...
                'Tag', [tag, 'Max']);

% Sonify button
pos = [19*CharWide pos(2)-pos(4)-1.5*CharHi buttonWidth ...
       buttonHeight];
h = uicontrol('Parent',  panel, ...
              'Style', 'pushbutton', ...
              'Units', 'Normalized',...
              'Position', [0.1 0 0.1 0.1], ...
              'String', 'Sonify', ...
              'Tag', 'SonifyButton', ...
              'Callback', @(src, ev)Sonify(obj, src));

% Export wavfile
pos(1) = pos(1) + pos(3) + 1;
h = uicontrol('Parent',  panel, ...
              'Style', 'pushbutton', ...
              'Units', 'Normalized',...
              'Position', [0.4 0 0.1 0.1], ...
              'String', 'Export .WAV', ...
              'Callback', 'SonifyExportWAV_Callback(gcbo,[],guidata(gcbo))');
