

%%%%%% Sonification panel
sonPos = [columnOneLeft+columnWidth+1  1*CharHi 2*columnWidth+1 18*CharHi];
handles.SonicPanel = uipanel('Parent', handles.OutputProcessingPanel, ...
                             'FontSize', 9, ...
                             'Title', 'Sonification', ...
                             'Units', 'Characters', ...
                             'Position', sonPos,  ...
                             'Tag', 'SonicPanel', ...
                             'Visible', 'on', ...
                             'BackgroundColor', bgColor);

startLeft = 3;
startBot  = 1;

sonicTextStr = ['Add inputs to sonify by selecting Timeseries ' ...
                'objects from the Data Objects list box.'];
                

pos = [2 14*CharHi 70*CharWide 2*CharHi];
s = uicontrol('Parent', handles.SonicPanel, ...
              'Style', 'text', ...
              'FontSize', 9, ...
              'Units', 'Characters', ...
              'Position', pos, ...
              'HorizontalAlignment', 'left',...
              'String', sonicTextStr, ...
              'BackgroundColor', bgColor);

% Min text
pos(2) = pos(2) - 1.5*CharHi;
pos(1) = 19*CharWide;
pos(3) = 4*CharWide;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Min.', ...
              'BackgroundColor', bgColor);

% Max text
pos(1) = pos(1) + 9*CharWide;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Max.', ...
              'BackgroundColor', bgColor);

pos(1) = pos(1) + 8*CharWide;
pos(3) = 25*CharWide;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'HorizontalAlignment', 'center', ...
              'String', 'Timeseries object', ...
              'BackgroundColor', bgColor);

% Checkbox for frequency only
cpos = [65*CharWide pos(2)+1*CharHi 25*CharWide CharHi];
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'checkbox', ...
              'Value', 1,...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', cpos, ...
              'String', 'Use pink noise', ...
              'BackgroundColor', bgColor,...
              'Tag', 'SonifyUsePinkNoise', ...
              'Callback', ...
     'PsySoundGUI(''SonifyUSePinkNoise_Callback'',gcbo,[],guidata(gcbo))');

sonicCellStrs = {'Frequency (Hz)', 'Level (dB)', 'Pan 0:L, 1:R'};
sonicCellTags = {'freq', 'level', 'pan'};

pos(1) = 2;
pos(2) = pos(2) + 0.5*CharHi;

for i=1:length(sonicCellStrs)
  str = sonicCellStrs{i};
  tag = sonicCellTags{i};

  rowPos = pos;
  
  % Text
  rowPos(2) = rowPos(2) - rowPos(4) - (i-1) * 2 * CharHi;
  rowPos(3) = 14*CharWide;
  h = uicontrol('Parent', handles.SonicPanel, ...
                'Style', 'text', ...
                'FontSize', 9, ...
                'Units', 'Characters', ...
                'Position', rowPos-[0 0.5 0 0], ...
                'HorizontalAlignment', 'right',...
                'String', str, ...
                'BackgroundColor', bgColor);
  
  % Min value
  rowPos(1) = rowPos(1)+rowPos(3)+CharWide;
  rowPos(3) = 8*CharWide;
  h = uicontrol('Parent',  handles.SonicPanel, ...
                'Style', 'edit', ...
                'Units', 'Characters',...
                'Fontsize', 9, ...
                'Position', rowPos, ...
                'String', '0', ...
                'Enable', 'off', ...
                'Tag', [tag, 'Min']);
                
  % Max value
  rowPos(1) = rowPos(1)+rowPos(3)+CharWide;
  rowPos(3) = 8*CharWide;
  h = uicontrol('Parent',  handles.SonicPanel, ...
                'Style', 'edit', ...
                'Units', 'Characters',...
                'Fontsize', 9, ...
                'Position', rowPos, ...
                'String', '0', ...
                'Enable', 'off', ...
                'Tag', [tag, 'Max']);

  % TSObj
  rowPos(1) = rowPos(1)+rowPos(3)+CharWide;
  rowPos(3) = 26*CharWide;
  h = uicontrol('Parent',  handles.SonicPanel, ...
                'Style', 'edit', ...
                'Units', 'Characters',...
                'Fontsize', 9, ...
                'Position', rowPos, ...
                'String', '', ...
                'Tag', [tag, 'TsObj']);

  % Add button
  rowPos(1) = rowPos(1)+rowPos(3)+CharWide;
  rowPos(3) = 0.6*buttonWidth;
  cbStr = ['''', 'SonifyAdd', tag, '_Callback', ''''];
  h = uicontrol('Parent',  handles.SonicPanel, ...
                'Style', 'pushbutton', ...
                'Units', 'Characters',...
                'Position', rowPos, ...
                'String', 'Add', ...
                'Callback', ...
  ['PsySoundGUI(', cbStr, ',gcbo,[],guidata(gcbo))']);

  % Remove button
  rowPos(1) = rowPos(1)+rowPos(3)+CharWide;
  rowPos(3) = 0.8*buttonWidth;
  cbStr = ['''', 'SonifyRemove', tag, '_Callback', ''''];
  h = uicontrol('Parent',  handles.SonicPanel, ...
                'Style', 'pushbutton', ...
                'Units', 'Characters',...
                'Position', rowPos, ...
                'String', 'Remove', ...
                'Callback', ...
           ['PsySoundGUI(', cbStr, ',gcbo,[],guidata(gcbo))']);

end

% Slight changes to the Pan min/max
h = findobj(handles.SonicPanel, '-regexp', 'Tag', 'pan(Min|Max)');
set(h, 'Enable', 'on', 'String', '1');

% Output file scaling
str = 'Output scaling factor:';
pos(1) = pos(1) + pos(4) + 5*CharWide;
pos(2) = rowPos(2) - 3.5*CharHi;
pos(3) = length(str)*CharWide;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'text', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'HorizontalAlignment', 'right',...
              'String', str, ...
              'BackgroundColor', bgColor);

% Duration scaling factor
pos(2) = pos(2) + 0.5*CharHi;
pos(1) = pos(1) + pos(3) + CharWide;
pos(3) = 3*CharWide;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'edit', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'HorizontalAlignment', 'right',...
              'String', '5', ...
              'Tag', 'outScFactor', ...
              'BackgroundColor', bgColor);

% Duration scaling factor popup
pos(1) = pos(1) + pos(3) + CharWide;
pos(2) = pos(2) - 0.25*CharHi;
pos(3) = 22*CharWide;
strs = {'no change', 'Total duration in secs', ' x upsample', ' x downsample'};
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'popup', ...
              'FontSize', 9,...
              'Units', 'Characters',...
              'Position', pos, ...
              'HorizontalAlignment', 'right',...
              'Tag', 'outScFactorPopup', ...
              'Value', 2, ...
              'String', strs, ...
              'BackgroundColor', bgColor);

% Clear all button
pos(1) = pos(1) + 26*CharWide;
pos(2) = pos(2) + 0.5*CharHi;
pos(3) = 1.4*buttonWidth + CharWide;

h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'pushbutton', ...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Clear all', ...
              'Callback', ...
         'PsySoundGUI(''SonifyClearAll_Callback'',gcbo,[],guidata(gcbo))');


% Sonify button
pos = [19*CharWide pos(2)-pos(4)-1.5*CharHi buttonWidth ...
       buttonHeight];
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'pushbutton', ...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Sonify', ...
              'Tag', 'SonifyButton', ...
              'Callback', ...
              'PsySoundGUI(''Sonify_Callback'',gcbo,[],guidata(gcbo))');

% Play input file
pos(1) = pos(1) + pos(3) + 1;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'pushbutton', ...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Play Input file', ...
              'Callback', ...
         'PsySoundGUI(''SonifyPlayInput_Callback'',gcbo,[],guidata(gcbo))');

% Play output file
pos(1) = pos(1) + pos(3) + 1;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'pushbutton', ...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Play Output file', ...
              'Callback', ...
       'PsySoundGUI(''SonifyPlayOutput_Callback'',gcbo,[],guidata(gcbo))');

% Export wavfile
pos(1) = pos(1) + pos(3) + 1;
h = uicontrol('Parent',  handles.SonicPanel, ...
              'Style', 'pushbutton', ...
              'Units', 'Characters',...
              'Position', pos, ...
              'String', 'Export .WAV', ...
              'Callback', ...
         'PsySoundGUI(''SonifyExportWAV_Callback'',gcbo,[],guidata(gcbo))');

end