function obj = ui(obj, panel)
% UI metod for basic summary
% 
% Basically a grid
%
% Inputs:
%  panel : is the handle to the left panel of the data analyser

bgColor = [0.9 0.9 0.9];

% Data dir info
pos = [0.03 0.8 0.9 0.1];
h = uicontrol('Parent', panel, ...
              'units', 'normalized', ...
              'Position', pos, ...
              'String',  'Psysound3 data directory ...', ...
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bgColor, ...              
              'Style',   'text');

obj.dataDir = h;

% Audio file info
lpos    = pos;
lpos(4) = 0.2;
lpos(2) = lpos(2) - lpos(4) - 0.015;
lpos(3) = 0.4;
h = uicontrol('Parent', panel, ...
              'units', 'normalized', ...
              'Position', lpos, ...
              'String',  'Audio file info ...', ...
              'BackgroundColor', bgColor, ...              
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'Style',   'text');

obj.fileInfo = h;

% Audio Analyser info
lpos(4) = 0.55;
lpos(2) = lpos(2) - lpos(4) - 0.01;
h = uicontrol('Parent', panel, ...
              'units', 'normalized', ...
              'Position', lpos, ...
              'String',  'Audio Analyser info ...', ...
              'BackgroundColor', bgColor, ...              
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'Style',   'text');

obj.AudioAnalyserInfo = h;

% Audio Analyser data info
rpos    = pos;
rpos(1) = rpos(1) + rpos(3)/2 + 0.01;
rpos(4) = 0.7;
rpos(2) = rpos(2) - rpos(4) - 0.01;
rpos(3) = 0.4;
h = uicontrol('Parent', panel, ...
              'units', 'normalized', ...
              'Position', rpos, ...
              'String',  'Data output from Audio Analyser ...', ...
              'BackgroundColor', bgColor, ...              
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'Style',   'text');

obj.AudioDataOutput = h;

% Audio Analyser data info
% rpos(4) = 0.4;
% rpos(2) = rpos(2) - rpos(4) - 0.01;
% h = uicontrol('Parent', panel, ...
%               'units', 'normalized', ...
%               'Position', rpos, ...
%               'String',  'Output form Data Analyser ...', ...
%               'BackgroundColor', bgColor, ...              
%               'FontSize', 9, ...
%               'HorizontalAlignment', 'left', ...
%               'Style',   'text');

% obj.DataAnalyserOutput = h;
end

% EOF
