function  ui(RLB, parent)
% Sets up the ui for the RLB Analyser. 
% usage: ui(RLB, parent)
% 
% We rely on picking up the Tag of the uicontrol objects later, so we only
% set them up, we don't return handles to each of them. We can get the handles 
% again in the settings method with handle = findobj('Tag','YourTagHere');
% 
% Make sure the tags you use are unique. The easiest way to do this is to
% use the name of the analyser in the tag at the start, as is done below. 

% Character width and heights
handles = guidata(parent);
cw = handles.CharWide;
ch = handles.CharHi;

textString = 'Choose block length for RMS calculation:';

uicontrol('Style', 'text', ...
          'FontSize', 9, ...
          'String', textString,...
          'Parent', parent, ...
          'Units', 'Characters', ...
          'Position', [1*cw 8*ch 46*cw 5.5*ch], ...
          'HorizontalAlignment', 'left', ...
          'BackgroundColor',[0.9 0.9 0.9]);

pos = [1*cw 4*ch 10*cw 1.5*ch];
uicontrol('Style', 'checkbox', ...
          'String', '10 s',...        
          'Parent', parent, ...
          'Tag', 'RLB10s', ...
          'Units', 'Characters', ...
          'Position', pos, ...
          'Value', 0, ...
          'BackgroundColor',[0.9 0.9 0.9]);

pos(2) = pos(2) + pos(4) + ch;
uicontrol('Style', 'checkbox', ...
          'String', '3 s',...        
          'Parent', parent, ...
          'Tag', 'RLB3s', ...
          'Units', 'Characters', ...
          'Position', pos, ...
          'Value', 0, ...
          'BackgroundColor',[0.9 0.9 0.9]);

pos(2) = pos(2) + pos(4) + ch;
uicontrol('Style', 'checkbox', ...
          'String', '1 s',...        
          'Parent', parent, ...
          'Tag', 'RLB1s', ...
          'Units', 'Characters', ...
          'Position', pos, ...
          'Value', 1, ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Ignore initial filter delay',...
          'Parent', parent, ...
          'Tag', 'RLBIgnoreDelay', ...
          'Units', 'Characters', ...
          'Value', 1, ...
          'Position', [1*cw 1*ch 30*cw 1.5*ch], ...
          'BackgroundColor',[0.9 0.9 0.9]);
      
% Position is [distanceFromLeft distanceFromBottom width height] 
% Units = Characters gives a certain amount of stability, although it may
% cause some problems on some platforms.