function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Implements many of the features of PsySound2.', ...
       'SUTABLE FOR AUDIO SR = 44.1 kHz ONLY!', ...
       'The code is adapted from the original', ... 
       'PsySound2 Pascal.', ...
       'The implementation includes the use of the', ...
       'compact spectrum to provide a computationally', ...
       'efficient solution to loudness calculation. ', ...
       ' ', ...
       'Outputs include: ', ...
       '* Loudness (Moore et al static model), ', ...
       '* Time varying specific loudness pattern, ', ...
       '* Time averaged specific loudness pattern, ', ...
       '* Sharpness (Zwicker & Fastl and Aures versions,',...
       '  using the specific loudness pattern from Moore et al.), ', ...
       '* Volume, ',...
       '* Spectral dissonance (Hutchinson & Knopoff and Sethares), ' ,...
       '* Tonal dissonance (H&K and Sethares). ', ...
       ' ', ...
       'Code by Densil Cabrera and Sam Ferguson.'};