function  ui(obj, parent)
% UI method for the Hilbert Analyser

% Character width and heights
handles = guidata(parent);
cw = handles.CharWide;
ch = handles.CharHi;

% Weightings' popup
  uicontrol('Style',               'popup', ...
            'FontSize',            9, ...
            'Parent',              parent, ...
            'Units',               'Characters', ...
            'Position',            [22*cw 16*ch 12*cw 2.2*ch],...
            'Value',               1, ...
            'String',              {'none', 'A', 'B', 'C', 'D'}, ...
            'Tag',                'HilbertWeightingType', ...
            'BackgroundColor',     [0.9 0.9 0.9]);
  
  uicontrol('Style',    'text', ...
            'FontSize', 9,      ...
            'Parent',   parent, ... 
            'Units',            'Characters', ...
            'Position',         [1*cw 16*ch 20*cw 2*ch],...
            'HorizontalAlignment', 'left', ...
            'String',          'Choose weighting: ', ...
            'BackgroundColor',  [0.9 0.9 0.9]);
           
  uicontrol('Style',    'text', ...
            'FontSize', 9,      ...
            'Parent',   parent, ... 
            'Units',            'Characters', ...
            'Position',         [1*cw 12*ch 25*cw 3*ch],...
            'HorizontalAlignment', 'left', ...
            'String',          'Note: this will add to computation time. ', ...
            'BackgroundColor',  [0.9 0.9 0.9]);
           
% EOF
