function obj = ui(obj, panel)
% UI method for Basic Plot
%
% Inputs:
% panel : is the handle to the left panel of the data analyser

bgColor = [0.9 0.9 0.9];

%%%%%%%%%%%%%%
% Univariate %
%%%%%%%%%%%%%%
univPanel = uipanel('Parent',panel, ...
                    'Title','Univariate Data', ...
                    'units',    'normalized', ...         
                    'Tag','UnivariatePanel', ...                      
                    'BackGroundColor', bgColor, ...
                    'FontSize',9, ...
                    'Position', [0.65 0.7 0.33 0.2]);

% Add the UV push-button
uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.7 0.05 0.25 0.25], ...
          'String',  'Graph', ...
          'Enable',  'on', ...
          'ToolTip', 'Creates representation', ...
          'BackGroundColor', bgColor, ...              
          'Callback', @(src, ev)UVCallback(obj, src), ...
          'Tag',      '1DButton', ...
          'Style',   'Pushbutton');

% Add the Popupmenu
uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.05 0.7 0.6 0.25], ...
          'String',  'Cumulative Distribution|Boxplot|Histogram|Density|Median|Max|Min|Mean|Percentile', ...
          'Enable',  'on', ...
          'ToolTip', 'Choose representation', ...
          'BackGroundColor', bgColor, ...              
          'Tag',      'UnivariatePopup', ...
          'Style',   'popupmenu');       

% Add the Popupmenu
uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.65 0.7 0.3 0.25], ...
          'String',  '1|2|3|4|5|10|25|50|75|90|95|96|97|98|99', ...
          'Enable',  'on', ...
          'ToolTip', 'Percentile', ...
          'BackGroundColor', bgColor, ...              
          'Tag',      'UnivariatePctlPopup', ...
          'Style',   'popupmenu');               

% Decimation        
uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.02 0.4 0.55 0.2], ...
          'String',  'Decimate to:', ...
          'Enable',  'on', ...
          'ToolTip', 'Decimate the data to a pre-specified duration.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'decimateCheckbox', ...
          'Style',   'checkbox');

uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.45 0.4 0.3 0.2], ...
          'String',  '1|2|5|10|20', ...
          'Enable',  'on', ...
          'ToolTip', 'Decimate the data to a pre-specified duration.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'decimatePopup', ...
          'Style',   'popupmenu');

uicontrol('Parent',   univPanel, ...
          'units',    'normalized', ...
          'Position', [0.75 0.35 0.15 0.2], ...
          'String',  'sec', ...
          'Enable',  'on', ...
          'ToolTip', 'Decimate the data to a pre-specified duration.', ...
          'BackGroundColor', bgColor, ...             
          'HorizontalAlignment','left', ...
          'Style',   'text');

        
%%%%%%%%%%%%%        
% Bivariate %
%%%%%%%%%%%%%

bvPanel = uipanel('Parent',panel, ...
                  'Title','Bivariate Data', ...
                  'units',    'normalized', ...         
                  'BackGroundColor', bgColor, ...
                  'Tag','BivariatePanel', ...  
                  'FontSize',9, ...
                  'Position', [0.65 0.47 0.33 0.2]);

uicontrol('Parent',   bvPanel, ...
          'units',    'normalized', ...
          'Position', [0.05 0.7 0.7 0.25], ...
          'String',  'Regression|Threshold - Univariate', ...
          'Enable',  'on', ...
          'ToolTip', 'Choose Representation', ...
          'BackGroundColor', bgColor, ...              
          'Tag',      'BivariatePopup', ...
          'Style',   'popupmenu');       
                        
% Add the Regression push-button
uicontrol('Parent',   bvPanel, ...
          'units',    'normalized', ...
          'Position',  [0.7 0.05 0.25 0.25], ...
          'String',  'Graph', ...
          'Enable',  'on', ...
          'ToolTip', 'Compare 2 results', ...
          'BackGroundColor', bgColor, ...              
          'Callback', @(src, ev)BVCallback(obj, src), ...
          'Tag',      '2DButton', ...
          'Style',   'Pushbutton');

uicontrol('Parent',   bvPanel, ...
          'units',    'normalized', ...
          'Position', [0.25 0.15 0.3 0.3], ...
          'String',  '100', ...
          'Enable',  'on', ...
          'ToolTip', 'Flatten at which number.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'flattenEditText', ...
          'Style',   'edit');

%%%%%%%%%%%%%%
% Timeseries %
%%%%%%%%%%%%%%

% Add fourier transform button.
tsPanel = uipanel('Parent',panel, ...
                  'Title','Timeseries Data', ...
                  'units',    'normalized', ...         
                  'BackGroundColor', bgColor, ...
                  'Tag','TimeseriesPanel', ...  
                  'FontSize',9, ...
                  'Position', [0.65 0.25 0.33 0.2]);
                                                      
uicontrol('Parent',   tsPanel, ...
          'units',    'normalized', ...
          'Position', [0.05 0.7 0.7 0.25], ...
          'String',  'Peak Analysis|Fourier Transform|Median Filter', ...
          'Enable',  'on', ...
          'ToolTip', 'Choose Representation', ...
          'BackGroundColor', bgColor, ...              
          'Tag',      'TimeseriesPopup', ...
          'Style',   'popupmenu');       
                        
% Add the GRAPH push-button
uicontrol('Parent',   tsPanel, ...
          'units',    'normalized', ...
          'Position',  [0.7 0.05 0.25 0.25], ...
          'String',  'Graph', ...
          'Enable',  'on', ...
          'ToolTip', 'Analyse Timeseries data', ...
          'BackGroundColor', bgColor, ...              
          'Callback', @(src, ev)TSCallback(obj, src), ...
          'Tag',      '2DButton', ...
          'Style',   'Pushbutton');                  

uicontrol('Parent',   tsPanel, ...
          'units',    'normalized', ...
          'Position', [0.05 0.4 0.5 0.25], ...
          'String',  'Stereo|Stereo Only|Peaks|Peaks Only|Troughs|Troughs Only', ...
          'Enable',  'on', ...
          'ToolTip', 'Choose which type of concatenation.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'tsConcatPopup', ...
          'Style',   'popupmenu');



%%%%%%%%%%%%%%
% Spectral %
%%%%%%%%%%%%%%

spPanel = uipanel('Parent',panel, ...
                  'Title','Spectral Data', ...
                  'units',    'normalized', ...         
                  'BackGroundColor', bgColor, ...
                  'Tag','SpectralPanel', ...  
                  'FontSize',9, ...
                  'Position', [0.65 0.02 0.33 0.2]);

uicontrol('Parent',   spPanel, ...
          'units',    'normalized', ...
          'Position', [0.05 0.7 0.7 0.25], ...
          'String',  'Average Spectrum|Beat Spectrum - Original|Beat Spectrum - CDF|Beat Spectrum - Max|Beat Spectrum - Median|Beat Spectrum - Min|Gain Function', ...
          'Enable',  'on', ...
          'ToolTip', 'Choose Representation', ...
          'BackGroundColor', bgColor, ...              
          'Tag',      'SpectralSonPopup', ...
          'Style',   'popupmenu');       
                        
% Add the GRAPH push-button
uicontrol('Parent',   spPanel, ...
          'units',    'normalized', ...
          'Position', [0.7 0.05 0.25 0.25], ...
          'String',  'Graph', ...
          'Enable',  'on', ...
          'ToolTip', 'Analyse Spectral data', ...
          'BackGroundColor', bgColor, ...              
          'Callback', @(src, ev)SPCallback(obj, src), ...
          'Tag',      '2DButton', ...
          'Style',   'Pushbutton');  

% Decimation        
uicontrol('Parent',   spPanel, ...
          'units',    'normalized', ...
          'Position', [0.02 0.4 0.55 0.2], ...
          'String',  'Decimate by:', ...
          'Enable',  'on', ...
          'ToolTip', 'Decimate the data by a specified factor.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'decimateCheckboxSP', ...
          'Style',   'checkbox');

uicontrol('Parent',   spPanel, ...
          'units',    'normalized', ...
          'Position', [0.45 0.4 0.3 0.2], ...
          'String',  '1|2|4|8|16', ...
          'Enable',  'on', ...
          'ToolTip', 'Decimate the data to a pre-specified duration.', ...
          'BackGroundColor', bgColor, ...              
          'Tag',     'decimatePopupSP', ...
          'Style',   'popupmenu');

          

%%%%%%%%        
% Axes %
%%%%%%%%

% Add axis
ax1 = axes('Parent', panel, ...
          'Units', 'normalized', ...
          'Tag',   'ESAAxesTop', ...
          'OuterPosition',      [0 0.5 0.65 0.4]);
        
ax2 = axes('Parent', panel, ...
          'Units', 'normalized', ...
          'Tag',   'ESAAxesBottom', ...
          'OuterPosition',      [0 0.05 0.65 0.4]);
 
% Add context menu
AddVisContextMenu(ax1); 
AddVisContextMenu(ax2);

function AddVisContextMenu(ax)
  
  % Create a default menu
  uih = uicontextmenu;

  % Add items
  % uimenu(uih, ...
  %        'Label',    'Grid',...  
  %        'Enable',   'off', ...
  %        'Tag',      'grid', ...
  %        'Callback', @gridCallback);
  % 
  % uimenu(uih, ...
  %        'Label',    'Legend', ...
  %        'Enable',   'off', ...
  %        'Tag',      'legend', ...
  %        'Callback', @legendCallback);

  uimenu(uih, ...
         'Label',     'Open new figure', ...
         'Enable',    'on', ...
         'Callback',   @newFigCallback, ...
         'Tag',       'newFig', ...
         'Separator', 'on');
	
  set(ax, 'UIContextMenu', uih);
  
% % end AddVisContextMenu

%%%%%%%%%%%%%%%%%%%%%%%%%%
% Context menu callbacks %
%%%%%%%%%%%%%%%%%%%%%%%%%%
% function gridCallback(varargin)
%   
%   h = varargin{1};
%   
%   % Find the axes
%   f  = get(get(h, 'Parent'), 'Parent');
%   ax = findobj(f, 'Type', 'Axes', 'Tag', 'SingleAxes');
%   
%   str = get(ax, 'XGrid');
%   if strcmp(str, 'on')
%     % Turn it off
%     grid(ax, 'off');
%     set(h, 'Checked', 'off');
%   else
%     % Turn it on
%     grid(ax, 'on');
%     set(h, 'Checked', 'on');
%   end    
% end gridCallback
% 
% %
% % legendCallback
% %
% function legendCallback(varargin)
%   
%   h = varargin{1};
% 
%   % Find the axes
%   f  = get(get(h, 'Parent'), 'Parent');
%   lg = findobj(f, 'Type', 'Axes', 'Tag', 'legend');
%   ax = findobj(f, 'Type', 'Axes', 'Tag', 'SingleAxes');
%   
%   if ~isempty(lg)
%     % Turn it off
%     legend off;
%     set(h, 'Checked', 'off');
%   else
%     % Turn it on
%     strs = get(ax, 'UserData');
%     legend(ax, strs);
%     set(h, 'Checked', 'on');
%   end    
% % end legendCallback
% 
% %
% % newFigCallback
% %

function newFigCallback(varargin)
  h = varargin{1};

  % Find the axes
  f  = get(get(h, 'Parent'), 'Parent');
  ax1 = findobj(f, 'Type', 'Axes', 'Tag', 'ESAAxesTop');
  ax2 = findobj(f, 'Type', 'Axes', 'Tag', 'ESAAxesBottom');
  % Clone into a new figure
  newFig = figure;
  newAx1 = copyobj(ax1, newFig);
  set(newAx1, 'Position', [0.1 0.6 0.8 0.35]);
  newAx2 = copyobj(ax2, newFig);
  set(newAx2, 'Position', [0.1 0.1 0.8 0.35]);
  
  % Fix dimensions
  
% end newFigCallback
%   
% 
% % EOF
