function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Performs a 1/3-octave band analysis', ...
    'of the input wave ', ...
    'and outputs the 1/3-octave band', ...
    'time-spectrum and spectrum,', ...
       'and specific loudness pattern', ...
       'following ISO532B (Zwicker method).'};