function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Performs pitch analysis using Ernst Terhardt''s', ...
    'virtual pitch theory, as described in:', ...
    ' ', ...
    'E. Terhardt, G. Stoll, and M. Seewan (1982)', ...
    '"Algorithm for extraction of ', ...
    'pitch and pitch salience from complex tonal signals,"', ...
    'J. Acoust. Soc. Am. 71:679-688.', ...
    ' ', ...
    'The output of Terhardt''s pitch algorithm is analysed ', ...
    'based on concepts developed in Richard Parncutt''s', ...
    '"Harmony: A Psychoacoustical Approach"', ...
    'Springer-Verlag, 1989. ', ...
    ' ', ...
    'Outputs are:', ...
    '* Spectral pitch pattern', ...
    '* Virtual pitch pattern', ...
    '* Pure tonalness', ...
    '* Complex tonalness', ...
    '* Multiplicity', ...
    '* Salience (Parncutt) pattern', ...
    '* Chroma pattern', ...
    ' ', ...
    'Adapted in part from C code provided by Ernst Terhardt'};   

