function obj = ui(obj, panel)
% UI method for Basic Plot
%
% Inputs:
%  panel : is the handle to the left panel of the data analyser

bgColor = [0.9 0.9 0.9];

% Add the Graph push-button
uicontrol('Parent',   panel, ...
          'units',    'normalized', ...
          'Position', [0.8 0.1 0.17 0.07], ...
          'String',  'Graph', ...
          'Enable',  'on', ...
          'ToolTip', 'Plots graph', ...
          'BackGroundColor', bgColor, ...              
          'Callback', @(src, ev)Graph(obj, src), ...
          'Tag',      'GraphButton', ...
          'Style',    'Pushbutton');

% Add axis
ax = axes('Parent', panel, ...
          'Units', 'normalized', ...
          'Tag',   'Axes', ...
          'OuterPosition',      [0 0 0.8 0.95]);

% EOF
