function obj = ui(obj, panel)
% UI method for Data Analyser.  This is a default method that
%    provides a single pushbutton for convenience.
%
% Inputs:
%  panel : is the handle to the left panel of the data analyser

% Add Execute push-button
uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.8 0.04 0.17 0.07], ...
          'String',  'Process', ...
          'Tag',     'ProcessButton', ...
          'Callback', @(src, ev)process(obj, src), ...
          'ToolTip', ['Executes ', obj.Name], ...
          'Style',   'Pushbutton');
