function obj = ui(obj, panel)
% UI method for Data Analyser.  This is a default method that
%    provides a single pushbutton for convenience.
%
% Inputs:
%  panel : is the handle to the left panel of the data analyser

bgColor = [0.9 0.9 0.9];

% Add Execute push-button
uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.2 0.34 0.17 0.07], ...
          'String',  'Downsample', ...
          'Tag',     'DownsampleButton', ...
          'Callback', @(src, ev)process(obj, src), ...          
          'Style',   'Pushbutton');

% Add P and Q texts and edits
uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.2 0.45 0.05 0.05], ...
          'BackGroundColor', bgColor, ...              
          'String',  'Q :', ...
          'HorizontalAlignment', 'right', ...
          'Style',   'Text');

uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.2 0.5 0.05 0.05], ...
          'String',  'P :', ...
          'BackGroundColor', bgColor, ...              
          'HorizontalAlignment', 'right', ...
          'Style',   'Text');

uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.27 0.455 0.1 0.05], ...
          'BackGroundColor', bgColor, ...              
          'String',  '1', ...
          'Tag', 'QValue', ...
          'HorizontalAlignment', 'left', ...
          'Style',   'edit');

uicontrol('Parent', panel, ...
          'units', 'normalized', ...
          'Position', [0.27 0.505 0.1 0.05], ...
          'String',  '1', ...
          'BackGroundColor', bgColor, ...              
          'Tag', 'PValue', ...
          'HorizontalAlignment', 'left', ...
          'Style',   'edit');

% EOF
