function out = getDataObjectStatsString(obj)
% GETDATAOBJECTSTATSSTRING  Formats and returns stats string
%

out = '';

% Data
str{1} = sprintf('%s (%s):\n', obj.DataName, obj.DataUnit);
stats  = get(obj, 'Stats');
str{end+1} = sprintf(['  Min. : %.2f\n', ...
                    '  Max. : %.2f\n', ...
                    '  Median : %.2f\n', ...
                    '  Average : %.2f\n', ...
                    '  St. dev.. : %.2f\n'], ...
                     stats.min,...
                     stats.max,...
                     stats.median,...
                     stats.mean,...
                     stats.stdev);

str{end+1} = sprintf('\n');
str{end+1} = getFreqStr(obj);

out = [str{:}];
