function  ui(SLM, parent)
% Sets up the ui for the SLM Analyser. 
% usage: ui(SLM, parent)
% 
% We rely on picking up the Tag of the uicontrol objects later, so we only
% set them up, we don't return handles to each of them. We can get the handles 
% again in the settings method with handle = findobj('Tag','YourTagHere');
% 
% Make sure the tags you use are unique. The easiest way to do this is to
% use the name of the analyser in the tag at the start, as is done below. 

% Character width and heights
handles = guidata(parent);
cw = handles.CharWide;
ch = handles.CharHi;

textString = ['Tick the Weighting Filters that you would ' ...
    'like used. '];

uicontrol('Style', 'text', ...
          'String', textString, ...
          'FontSize', 9,...
          'Parent', parent, ...
          'Units', 'Characters', ...
          'Position', [1*cw 22*ch 46*cw 2*ch], ...
          'HorizontalAlignment', 'left', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Z (unweighted)',...        
          'Parent', parent, ...
          'Tag', 'SLMWeighting Z', ...
          'Units', 'Characters', ...
          'Position', [1*cw 20.5*ch 20*cw 1.5*ch], ...
          'Value', 1, ...
          'UserData', 'Z', ...
          'BackgroundColor', [0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'A Weighting',...        
          'Parent', parent, ...
          'Tag', 'SLMWeighting A', ...
          'Units', 'Characters', ...
          'Position', [1*cw 19*ch 20*cw 1.5*ch], ...
          'Value', 1, ...
          'UserData', 'A', ...
          'BackgroundColor', [0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String','B Weighting',...        
          'Parent', parent, ...
          'Tag', 'SLMWeighting B', ...
          'Units', 'Characters', ...
          'Position', [1*cw 17.5*ch 20*cw 1.5*ch], ...
          'Value', 0, ...
          'UserData', 'B', ...
          'BackgroundColor', [0.9 0.9 0.9]);

uicontrol('Style','checkbox', ...
          'String', 'C Weighting',...        
          'Parent', parent, ...
          'Tag', 'SLMWeighting C', ...
          'Units', 'Characters', ...
          'Position', [1*cw 16*ch 20*cw 1.5*ch], ...
          'Value', 0, ...
          'UserData', 'C', ...
          'BackgroundColor',[0.9 0.9 0.9]);
        
        uicontrol('Style','checkbox', ...
          'String', 'RLB Weighting',...        
          'Parent', parent, ...
          'Tag', 'SLMWeighting R', ...
          'Units', 'Characters', ...
          'Position', [1*cw 14.5*ch 20*cw 1.5*ch], ...
          'Value', 0, ...
          'UserData', 'R', ...
          'BackgroundColor',[0.9 0.9 0.9]);

textString = ['Integration time can be ''peak'' (50us), ''impulse'' (35ms), ''fast'' (125ms) ' ...
    ', ''slow'' (1s). A longer integration time ', ...
    'results in a smoother output, but de-emphasises '...
    'short term changes in level.'];

uicontrol('Style', 'text', ...
          'FontSize', 9, ...
          'String', textString,...
          'Parent', parent, ...
          'Units', 'Characters', ...
          'Position', [1*cw 8*ch 46*cw 5.5*ch], ...
          'HorizontalAlignment', 'left', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Fast',...        
          'Parent', parent, ...
          'Tag', 'SLMIntegration f', ...
          'Units', 'Characters', ...
          'Position', [1*cw 5*ch 15*cw 1.5*ch], ...
          'Value', 1, ...
          'UserData', 'f', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Slow',...
          'Parent', parent, ...
          'Tag', 'SLMIntegration s', ...
          'Units', 'Characters', ...
          'Position', [1*cw 3.5*ch 15*cw 1.5*ch], ...
          'UserData', 's', ...          
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Impulse',...        
          'Parent', parent, ...
          'Tag', 'SLMIntegration i', ...
          'Units', 'Characters', ...
          'Position', [1*cw 6.5*ch 15*cw 1.5*ch], ...
          'UserData', 'i', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'Peak',...
          'Parent', parent, ...
          'Tag', 'SLMIntegration p', ...
          'Units', 'Characters', ...
          'Position', [1*cw 8*ch 15*cw 1.5*ch], ...
          'UserData', 'p', ...          
          'BackgroundColor',[0.9 0.9 0.9]);  
    

uicontrol('Style', 'checkbox', ...
          'String', 'RMS 125ms',...        
          'Parent', parent, ...
          'Tag', 'SLMIntegration r0.125', ...
          'Units', 'Characters', ...
          'Position', [20*cw 8*ch 15*cw 1.5*ch], ...
          'Value', 1, ...
          'UserData', 'r0.125', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'RMS 1s',...        
          'Parent', parent, ...
          'Tag', 'SLMIntegration r1', ...
          'Units', 'Characters', ...
          'Position', [20*cw 6.5*ch 15*cw 1.5*ch], ...
          'Value', 1, ...
          'UserData', 'r1', ...
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'RMS 3s',...
          'Parent', parent, ...
          'Tag', 'SLMIntegration r3', ...
          'Units', 'Characters', ...
          'Position', [20*cw 5*ch 15*cw 1.5*ch], ...
          'UserData', 'r3', ...          
          'BackgroundColor',[0.9 0.9 0.9]);

uicontrol('Style', 'checkbox', ...
          'String', 'RMS 10s',...        
          'Parent', parent, ...
          'Tag', 'SLMIntegration r10', ...
          'Units', 'Characters', ...
          'Position', [20*cw 3.5*ch 15*cw 1.5*ch], ...
          'UserData', 'r10', ...
          'BackgroundColor',[0.9 0.9 0.9]);


uicontrol('Style', 'checkbox', ...
          'String', 'Ignore initial filter delay',...
          'Parent', parent, ...
          'Tag', 'SLMIgnoreDelay', ...
          'Units', 'Characters', ...
          'Value', 1, ...
          'Position', [1*cw 1*ch 30*cw 1.5*ch], ...
          'BackgroundColor',[0.9 0.9 0.9]);
      
% Position is [distanceFromLeft distanceFromBottom width height] 
% Units = Characters gives a certain amount of stability, although it may
% cause some problems on some platforms.