function str = getDescription(obj)
% GETDESCRIPTION Returns a text string of the description

str = {'Derives 1/3-octave and octave band spectra using FFT. ', ...
    ' for 1 and 2 channel files', ...
    'Outputs are:', ...
    '* 1/3-octave band spectrogram', ...
    '* 1/3-octave band spectrum,', ...
    '* Octave band spectrogram', ...
    '* Octave band spectrum,', ...
    '* Average & difference spectra for 2-chan files'};
